#
# Copyright (c) 2001 by Sun Microsystems, Inc.
# All rights reserved.
#

#
# Copyright (c) 2007 NEC Corporation
#

include ../Makefile.com

# ZDEFS should be defined as empty because allow_severity and deny_severity
# will be undefined symbol. They will be defined by application.
ZDEFS	=

install: all $(ROOTLIBS) .WAIT $(ROOTLINKS) $(ROOTLINT) $(ROOTSFWSRCFILES)
