#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 2007 NEC Corporation
# All rights reserved.
#

PATH=/sbin:/usr/sbin:/usr/bin

if [ -d /etc/rc1.d ]; then
	if [ -f /tmp/rc-1st-call ]; then
		for f in /etc/rc1.d/K*; do
			if [ -s $f ]; then
				$f stop 
			fi
		done
	else
		> /tmp/rc-1st-call
	fi

	for f in /etc/rc1.d/S*; do
		if [ -s $f ]; then
			$f start 
		fi
	done
fi

exit 0
