#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 2009 NEC Corporation
# All rights reserved.
#

RAMDISK='/devices/ramdisk:a'
BOOTDEV='/ramdisk:a'

readmnttab() {
	while read special mountp fstype mntopts mnttime; do
		[ "x$mountp" = "x$1" ] && break
	done
}

case "$1" in
'start')

	readmnttab / < /etc/mnttab
	if [ "$fstype" != ufs ] ; then
		echo "ERROR: filesystem type is not ufs. fstype = $fstype"
		exit 1
	fi
	if [ "$special" != "$BOOTDEV" ] ; then
		echo "ERROR: device is not ramdisk. special = $special"
		exit 1
	fi

	/sbin/mount -F ufs -o remount,rw $RAMDISK /
	;;

'stop')
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
