#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 2008 NEC Corporation
# All rights reserved.
#

GOPT=

case "$1" in
'start')
	if [ ! -f /etc/syslog.conf ]; then
		echo "/etc/syslog.conf is missing. Exiting."
		exit 1
	fi

	if [ ! -x /usr/sbin/syslogd ]; then
		echo "Executable /usr/sbin/syslogd not found. Exiting"
		exit 1
	fi

	if [ -f /etc/syslog_gm.conf ]; then
		GOPT="-g"
	fi

	if [ ! -f /var/adm/messages ]; then
		/usr/bin/touch /var/adm/messages
		/usr/bin/chmod 0644 /var/adm/messages	
	fi

	/usr/sbin/syslogd ${GOPT} >/dev/msglog 2>&1

	exit 0
	;;

'stop')
	/usr/bin/pkill -u 0 syslogd
	exit 0
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
