#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

#
# Copyright (c) 2007 NEC Corporation
#


@ MSG_EF_ARM_RELEXEC		"EF_ARM_RELEXEC"
@ MSG_EF_ARM_HASENTRY		"EF_ARM_HASENTRY"
@ MSG_EF_ARM_INTERWORK		"EF_ARM_INTERWORK"
@ MSG_EF_ARM_APCS_26		"EF_ARM_APCS_26"
@ MSG_EF_ARM_APCS_FLOAT		"EF_ARM_APCS_FLOAT"
@ MSG_EF_ARM_PIC		"EF_ARM_PIC"
@ MSG_EF_ARM_ALIGN8		"EF_ARM_ALIGN8"
@ MSG_EF_ARM_NEW_ABI		"EF_ARM_NEW_ABI"
@ MSG_EF_ARM_OLD_ABI		"EF_ARM_OLD_ABI"
@ MSG_EF_ARM_SOFT_FLOAT		"EF_ARM_SOFT_FLOAT"
@ MSG_EF_ARM_VFP_FLOAT		"EF_ARM_VFP_FLOAT"
@ MSG_EF_ARM_MAVERICK_FLOAT	"EF_ARM_MAVERICK_FLOAT"
@ MSG_EF_ARM_BE8		"EF_ARM_BE8"
@ MSG_EF_ARM_EABI_VER1		"EF_ARM_EABI_VER1"
@ MSG_EF_ARM_EABI_VER2		"EF_ARM_EABI_VER2"
@ MSG_EF_ARM_EABI_VER3		"EF_ARM_EABI_VER3"
@ MSG_EF_ARM_EABI_VER4		"EF_ARM_EABI_VER4"
@ MSG_EF_ARM_EABI_VER5		"EF_ARM_EABI_VER5"
