#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

#
# Copyright (c) 2007 NEC Corporation
#

include ../Makefile.com

install: all $(ROOTLIBDIR) .WAIT $(ROOTLIBS)
