#
# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

#
# Copyright (c) 2006-2007 NEC Corporation
#

# ident	"@(#)Makefile	1.1	03/07/16 SMI"
#
# lib/sasl_plugins/plain/arm/Makefile

include ../Makefile.com

install: all $(ROOTLIBS)
