#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

#
# Copyright (c) 2006-2009 NEC Corporation
#

LIBRARY =	libm.a

VERS =		.2

COBJS =			\
	__cos.o		\
	__lgamma.o	\
	__libx_errno.o	\
	__rem_pio2.o	\
	__rem_pio2m.o	\
	__sin.o		\
	__sincos.o	\
	__xpg6.o	\
	_lib_version.o	\
	_SVID_error.o	\
	_TBL_ipio2.o	\
	_TBL_sin.o	\
	acos.o		\
	acosh.o		\
	asin.o		\
	asinh.o		\
	atan.o		\
	atan2.o		\
	atan2pi.o	\
	atanh.o		\
	cbrt.o		\
	ceil.o		\
	cos.o		\
	cosh.o		\
	erf.o		\
	exp10.o		\
	exp2.o		\
	expm1.o		\
	floor.o		\
	gamma.o		\
	gamma_r.o	\
	hypot.o		\
	j0.o		\
	j1.o		\
	jn.o		\
	lgamma.o	\
	lgamma_r.o	\
	log.o		\
	log10.o		\
	log1p.o		\
	log2.o		\
	logb.o		\
	matherr.o	\
	pow.o		\
	scalb.o		\
	signgam.o	\
	significand.o	\
	sin.o		\
	sincos.o	\
	sincospi.o	\
	sinh.o		\
	sqrt.o		\
	tan.o		\
	tanh.o		\
	__tan.o		\
	_TBL_tan.o	\
	_TBL_log2.o	\
	_TBL_exp2.o	\
	_TBL_atan.o	\
	_TBL_log.o	\
	_signbit.o	\
	__swapRD.o	\
	isinf.o

QOBJS =	__cosl.o	\
	__lgammal.o	\
	__poly_libmq.o	\
	__rem_pio2l.o	\
	__sincosl.o	\
	__sinl.o	\
	__tanl.o	\
	_TBL_atanl.o	\
	_TBL_cosl.o	\
	_TBL_ipio2l.o	\
	_TBL_sinl.o	\
	_TBL_tanl.o	\
	acoshl.o	\
	acosl.o		\
	asinhl.o	\
	asinl.o		\
	atan2l.o	\
	atan2pil.o	\
	atanhl.o	\
	atanl.o		\
	cbrtl.o		\
	copysignl.o	\
	coshl.o		\
	cosl.o		\
	erfl.o		\
	exp10l.o	\
	exp2l.o		\
	expl.o		\
	fabsl.o		\
	floorl.o	\
	fmodl.o		\
	gammal.o	\
	gammal_r.o	\
	hypotl.o	\
	ilogbl.o	\
	j0l.o		\
	j1l.o		\
	jnl.o		\
	lgammal.o	\
	lgammal_r.o	\
	log10l.o	\
	log1pl.o	\
	log2l.o		\
	logbl.o		\
	logl.o		\
	nextafterl.o	\
	remainderl.o	\
	rintl.o		\
	rndintl.o	\
	scalbl.o	\
	scalbnl.o	\
	signgaml.o	\
	significandl.o	\
	sincosl.o	\
	sincospil.o	\
	sinhl.o		\
	sinl.o		\
	sinpil.o	\
	sqrtl.o		\
	tanhl.o		\
	tanl.o		\
	finitel.o	\
	isnanl.o	\
	expm1l.o	\
	_TBL_expl.o	\
	_TBL_logl.o	\
	_TBL_expm1l.o	\
	powl.o

ROBJS =			\
	_TBL_r_atan_.o	\
	acosf.o		\
	acoshf.o	\
	asinf.o		\
	asinhf.o	\
	atan2f.o	\
	atan2pif.o	\
	atanf.o		\
	atanhf.o	\
	besself.o	\
	cbrtf.o		\
	copysignf.o	\
	cosf.o		\
	coshf.o		\
	erff.o		\
	exp10f.o	\
	exp2f.o		\
	expf.o		\
	expm1f.o	\
	fabsf.o		\
	floorf.o	\
	fmodf.o		\
	gammaf.o	\
	gammaf_r.o	\
	hypotf.o	\
	ilogbf.o	\
	lgammaf.o	\
	lgammaf_r.o	\
	log10f.o	\
	log1pf.o	\
	log2f.o		\
	logbf.o		\
	logf.o		\
	nextafterf.o	\
	powf.o		\
	remainderf.o	\
	rintf.o		\
	scalbf.o	\
	scalbnf.o	\
	signgamf.o	\
	significandf.o	\
	sinf.o		\
	sinhf.o		\
	sincosf.o	\
	sincospif.o	\
	sqrtf.o		\
	tanf.o		\
	tanhf.o		\
	isnanf.o

SOBJS =			\
	copysign.o	\
	exp.o		\
	fabs.o		\
	fmod.o		\
	ilogb.o		\
	isnan.o		\
	nextafter.o	\
	remainder.o	\
	rint.o		\
	scalbn.o

m9xOBJS =		\
	frexp.o		\
	frexpf.o	\
	ldexp.o		\
	ldexpf.o	\
	llrint.o	\
	llrintf.o	\
	llround.o	\
	llroundf.o	\
	lrint.o		\
	lrintf.o	\
	lround.o	\
	lroundf.o	\
	modf.o		\
	modff.o		\
	round.o		\
	roundf.o	\
	trunc.o		\
	truncf.o	\

complexOBJS =

OBJECTS = $(COBJS) $(ROBJS) $(QOBJS) $(SOBJS) $(m9xOBJS) $(complexOBJS)

include ../../Makefile.lib

# install this library in the root filesystem
include ../../Makefile.rootfs

LIBS =	$(DYNLIB) $(LINTLIB)

LDLIBS +=	-lc

SRCDIR =	../common
$(LINTLIB) :=	SRCS=$(SRCDIR)/$(LINTSRC)

CPPFLAGS +=	-I../common/C -D_REENTRANT -DELFOBJ -DLIBM_BUILD -DLIBM_MT_FEX_SYNC -DCOMPARISON_MACRO_BUG -D__INLINE -D__LITTLE_ENDIAN -I../common/inc
ASFLAGS +=	-P -D_ASM $(CPPFLAGS)
$(DYNLIB) := ASFLAGS += $(AS_PICFLAGS)

MAPFILES	= mapfile-common mapfile-vers
VERS_SCRIPT	= vers-script

$(__GNULD)LDFLAGS.SO	+= --discard-all

.KEEP_STATE:

all: $(LIBS)
install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)

lint:   lintcheck

# build rules
pics/%.o: %.c
	$(COMPILE.c) -o $@ $<
	$(POST_PROCESS_O)

pics/%.o: %.s
	$(COMPILE.s) -o $@ $<
	$(POST_PROCESS_O)

pics/%.o: ../common/C/%.c
	$(COMPILE.c) -o $@ $<
	$(POST_PROCESS_O)

pics/%.o: ../common/Q/%.c
	$(COMPILE.c) -o $@ $<
	$(POST_PROCESS_O)

pics/%.o: ../common/R/%.c
	$(COMPILE.c) -o $@ $<
	$(POST_PROCESS_O)

pics/%.o: ../common/m9x/%.c
	$(COMPILE.c) -o $@ $<
	$(POST_PROCESS_O)

pics/%.o: ../common/complex/%.c
	$(COMPILE.c) -o $@ $<
	$(POST_PROCESS_O)

include ../../Makefile.targ
