#
# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

#
# Copyright (c) 2007 NEC Corporation
#

include ../Makefile.com

# Disable warnings.
CERRWARN	=

install: all
