#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#ident	"@(#)Makefile	1.7	07/01/04 SMI"
#

include ../Makefile.com

DATAFILES = depend i.preserve i.manifest

.KEEP_STATE:

all: $(FILES) preremove postinstall
install: all pkg

include ../Makefile.targ
