#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright (c) 2008 NEC Corporation
# All rights reserved.
#

# Message file for cross libld.

@ MSG_ARG_SYSROOT	"sysroot="

@ MSG_ARG_DETAIL_ZSYSROOT	"\t[-z sysroot=dir]\n\t\t\tuse `dir' as a \
				default root filesystem for\n\
				\t\t\tcross compiling.\n"

@ MSG_ARG_SYSROOT1ST	"sysrootfirst"

@ MSG_ARG_NOSYSROOT1ST	"nosysrootfirst"

@ MSG_ARG_NOSYSROOT	"nosysroot"
